AWSTemplateFormatVersion: '2010-09-09'
Description: NorthBay Labs cfn-custom-resources Custom::Secret random GUID secret sample template.
Parameters:
  CustomResourcesFunction:
    Description: The Lambda function name of the NorthBay Labs custom resources provider. Defaults to CFNCustomResourcesFunction.
    Type: String
    Default: CFNCustomResourcesFunction
  Environment:
    Type: String
    Default: dev
  KmsKeyId:
    Description: KMS Key ID, alias, or ARN to use to do the encryption when stored in the Parameter Store. Set to an empty string to use the default KMS Key. Default is no KMS Key ID (empty string).
    Type: String
    Default: ''
  Name:
    Description: The name of the secret.
    Type: String
    Default: /northbaylabs/test/my-secret-guid
  ReturnSecret:
    Description: If true will return the value of the stored secret in plain text. Default is false.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  RotateOnUpdate:
    Description: If true will generate a new random secret on update. Default is false.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Resources:
  RandomGuidSecret:
    Type: Custom::Secret
    Properties:
      Description: A random secret in GUID format.
      KmsKeyId: !Ref KmsKeyId
      Name: !Ref Name
      NoEcho: true
      ReturnSecret: !Ref ReturnSecret
      RotateOnUpdate: !Ref RotateOnUpdate
      SecretPattern: '[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{4}'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${CustomResourcesFunction}-${Environment}'
      Tags:
        -
          Key: ENV
          Value: !Ref Environment

Outputs:  
  SecretName:    
    Description: The name used to store the secret in the SSM Parameter Store.
    Value: !GetAtt RandomGuidSecret.Name
  SecretVersion:
    Description: The version of random GUID secret.
    Value: !GetAtt RandomGuidSecret.Version
  Secret:
    Description: The  value of the random GUID secret in plain text.
    Value: !GetAtt RandomGuidSecret.Secret