AWSTemplateFormatVersion: '2010-09-09'
Description: NorthBay Labs cfn-custom-resources Custom::LogGroupSubscription Lambda sample template.
Parameters:
  CustomResourcesFunction:
    Description: The Lambda function name of the NorthBay Labs custom resources provider. Defaults to CFNCustomResourcesFunction.
    Type: String
    Default: CFNCustomResourcesFunction
  DestinationFunction:
    Type: String
    Description: The Lambda function name to stream the CloudWatch log group events to.
    Default: CloudWatchLogsHandler
  Environment:
    Type: String
    Default: dev
  FilterPattern:
    Type: String
    Description: The filter pattern to filter log events with. Defaults to no filter pattern (blank).
    Default: ''
  ForceSubscription:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  LambdaFunction:
    Description: The Lambda function name to set the subscription filter for. Defaults to SimpleLambdaFunction.
    Type: String
    Default: SimpleLambdaFunction

Resources:
  LogGroupSubscriptionFilter:
    Type: Custom::LogGroupSubscription
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${CustomResourcesFunction }-${Environment}'
      DestinationArn: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${DestinationFunction}-${Environment}'
      FilterPattern: !Ref FilterPattern
      ForceSubscription: !Ref ForceSubscription
      LogGroupName: !Sub '/aws/lambda/${LambdaFunction}-${Environment}'

Outputs:
  SubscriptionFilterName:
    Description: The name of the subscription filter that was added to the log group.
    Value: !GetAtt LogGroupSubscriptionFilter.FilterName
  LogGroupName:
    Description: The name of the LogGroup that the subscription filter was added to.
    Value: !GetAtt LogGroupSubscriptionFilter.LogGroupName
