AWSTemplateFormatVersion: '2010-09-09'
Description: NorthBay Labs cfn-custom-resources Custom::Secret KMS encrypted secret sample template.
Parameters:
  CustomResourcesFunction:
    Description: The Lambda function name of the NorthBay Labs custom resources provider. Defaults to CFNCustomResourcesFunction.
    Type: String
    Default: CFNCustomResourcesFunction
  EncryptedSecret:
    Description: Base64 encoded KMS encrypted string, use the AWS CLI to generated a n encrypted string with KMS.
    Type: String
  Environment:
    Type: String
    Default: dev
  KmsKeyId:
    Description: KMS Key ID, alias, or ARN to use to do the encryption when storing the secret in the SSM Parameter Store.
                 Set to an empty string to use the default KMS Key. Default is no KMS Key ID (empty string).
    Type: String
    Default: ''
  Name:
    Description: The name used to store the secret in the SSM Parameter Store.
    Type: String
    Default: /northbaylabs/test/kms-encrypted-secret
  ReturnSecret:
    Description: If true will return the value of the stored secret in plain text. Default is false.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  RotateOnUpdate:
    Description: If true will generate a new version of the secret on update. Default is false.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Resources:
  KmsEncryptedSecret:
    Type: Custom::Secret
    Properties:
      Description: A KMS encrypted secret decrypted and stored as a SecureString in the SSM Parameter Store.
      EncryptedSecret: !Ref EncryptedSecret
      KmsKeyId: !Ref KmsKeyId
      Name: !Ref Name
      NoEcho: true
      ReturnSecret: !Ref ReturnSecret
      RotateOnUpdate: !Ref RotateOnUpdate
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${CustomResourcesFunction}-${Environment}'
      Tags:
        -
          Key: ENV
          Value: !Ref Environment

Outputs:  
  SecretName:    
    Description: The name used to store the secret in the SSM Parameter Store.
    Value: !GetAtt KmsEncryptedSecret.Name
  SecretVersion:
    Description: The version of the stored secret string.
    Value: !GetAtt KmsEncryptedSecret.Version
  Secret:
    Description: The value of the secret in plain text.
    Value: !GetAtt KmsEncryptedSecret.Secret